version: "3"

services:
  cache:
    image: redis/redis-stack
    restart: always
    environment:
      - UPSTASH_REDIS_REST_TOKEN=dev-mode
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./.docker/cache:/data
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: longpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: hourboost
    ports:
      - 6500:5432
    volumes:
      - ./.docker/postgres16:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/farm-service/Dockerfile
    restart: always
    ports:
      - 4000:4000
    networks:
      - app_network

networks:
  app_network:
    external: true

volumes:
  cache:
  postgres:
