version: "3"

services:
  cache:
    image: redis/redis-stack
    restart: always
    environment:
      - UPSTASH_REDIS_REST_TOKEN=dev-mode
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./.docker/cache:/data
volumes:
  cache:
